### ISSUE TITLE
README.md need to be modified

### ISSUE THREAD

**Issue by leeejjju** [NarinHan/24-Fshare#4]
## Fshare
Usage
./fshare 127.0.0.1: list
./fshare 127.0.0.1: get <directory_name_in_server_side/file_name> <directory_name_in_client_side>
./fshare 127.0.0.1: put <directory_name_in_server_side/file_name> <directory_name_in_client_side>

./fshared -p -d <directory_name_in_server_side>

this is current contents of README.md
but about the explain about command 'put', two args need to be changed like
./fshare 127.0.0.1: put <file_name_in_server_side> <directory_name_in_server_side>
for make it works.

but I have no idea which one should be modified, README or code...

**Comment by NarinHan** [comment]
README was written wrong. Sorry for the confusion.
